version: "3.3"

x-common-service: &common-service
  restart: always


services:
  api:
    <<: *common-service
    build:
      context: api/
      dockerfile: ./Dockerfile.dev
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_URI=redis://redis:6379/  
    volumes:
      - ./api/src:/app/src
      - ./api/log:/app/log
      - api-data:/data



  front:
    <<: *common-service
    build:
      context: front/
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./front/src:/app/src


  mongo:
    <<: *common-service
    image: mongo:latest
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
    command: ["--quiet",  "--logpath=/data/db/mongod.log" ]

  redis:
    <<: *common-service
    image: redis:latest
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  reverseproxy:
    <<: *common-service
    build:
      context: reverse-proxy/
      dockerfile: ./Dockerfile.dev
    depends_on:
      - api
      - front
    volumes:
      - ./reverse-proxy/log:/var/log/nginx
    ports:
      - 8080:80


volumes:
  db-data:
  redis-data:
  api-data:
