version: "3.3"

x-common-service: &common-service
  restart: always

services:
  api:
    <<: *common-service
    build:
      context: api/
      dockerfile: ./Dockerfile.prod
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/

    volumes:
      - ./api/log:/app/log



  front:
    <<: *common-service
    build:
      context: front/
      dockerfile: ./Dockerfile.prod

  mongo:
    <<: *common-service
    build:
      context: mongodb/
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./mongodb/mongod.conf
        target: /etc/mongod.conf 
      - type: bind
        source: ./mongodb/log
        target: /var/log/mongodb
      - type: bind
        source: ./mongodb/data
        target: /data/db
    command: ["mongod", "--config", "/etc/mongod.conf"] 


  reverseproxy:
    <<: *common-service
    build:
      context: reverse-proxy/
      dockerfile: ./Dockerfile.prod
    depends_on:
      - api
      - front
    volumes:
      - ./reverse-proxy/log:/var/log/nginx
      - type: bind
        source: "/etc/letsencrypt"
        target: "/etc/letsencrypt"
        read_only: true
    ports:
      - 443:443