version: "3.3"

x-common-service: &common-service
  restart: always

services:
  api:
    <<: *common-service
    build:
      context: api/
      dockerfile: ./Dockerfile.prod
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/

    volumes:
      - ./api/log:/app/log

  redis:
    <<: *common-service
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

 

  front:
    <<: *common-service
    build:
      context: front/
      dockerfile: ./Dockerfile.prod

  mongo:
    <<: *common-service
    image: mongo:latest
    volumes:
      - db-data:/data/db
    command: ["--quiet",  "--logpath=/data/db/mongod.log" ]

  


  reverseproxy:
    <<: *common-service
    build:
      context: reverse-proxy/
      dockerfile: ./Dockerfile.prod
    depends_on:
      - api
      - front
    volumes:
      - ./reverse-proxy/log:/var/log/nginx
      - type: bind
        source: "/etc/letsencrypt"
        target: "/etc/letsencrypt"
        read_only: true
    ports:
      - 443:443



volumes:
  db-data:
  redis-data:
