version: "3.3"

x-common-service: &common-service
  restart: always

services:
  api:
    <<: *common-service
    build:
      context: api/
      dockerfile: ./Dockerfile.prod
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/

    volumes:
      - ./log/api:/app/log



  front:
    <<: *common-service
    build:
      context: front/
      dockerfile: ./Dockerfile.prod



  mongo:
      <<: *common-service
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - ./mongodb/data:/app/db
        - ./log/mongodb:/var/log/mongodb
      command: mongod --dbpath /app/db --logpath /var/log/mongodb/mongod.log --logappend --setParameter diagnosticDataCollectionEnabled=false


  reverseproxy:
    <<: *common-service
    build:
      context: reverse-proxy/
      dockerfile: ./Dockerfile.prod
    depends_on:
      - api
      - front
    volumes:
      - ./log/reverse-proxy:/var/log/nginx
      - type: bind
        source: "/etc/letsencrypt"
        target: "/etc/letsencrypt"
        read_only: true
    ports:
      - 443:443