version: "3.3"
services:
  api:
    build:
      context: api/
      dockerfile: ./Dockerfile
    restart: always

  front:
    build:
      context: front/
      dockerfile: ./Dockerfile
    restart: always
  
  reverseproxy:
    build:
      context: reverse-proxy/
      dockerfile: ./prod.dockerfile
    volumes:
      - type: bind
        source: "/etc/letsencrypt"
        target: "/etc/letsencrypt"
        read_only: true
    ports:
      - 443:443
    restart: always
