version: "3.3"

x-common-service: &common-service
  restart: always


services:
  api:
    <<: *common-service
    build:
      context: api/
      dockerfile: ./Dockerfile.dev
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    volumes:
      - ./api/src:/app/src
      - ./log/api:/app/log


  front:
    <<: *common-service
    build:
      context: front/
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./front/src:/app/src


  mongo:
    <<: *common-service
    build: 
        context: .
        dockerfile: ./Dockerfile.mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/app/db
      - ./log/mongodb:/var/log/mongodb
    command: ["bash", "-c", "mkdir -p /var/log/mongodb && mongod --dbpath /app/db --logpath /var/log/mongodb/mongod.log --logappend --setParameter diagnosticDataCollectionEnabled=false"]

  
  
  reverseproxy:
    <<: *common-service
    build:
      context: reverse-proxy/
      dockerfile: ./Dockerfile.dev
    depends_on:
      - api
      - front
    volumes:
      - ./log/reverse-proxy:/var/log/nginx
    ports:
      - 8080:80
